// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj4sDYBp4cJ49jucr0i5sGCAyW7T3yQQs',
    appId: '1:1033120432288:web:c161b006e106bbb84209c5',
    messagingSenderId: '1033120432288',
    projectId: 'eventease-571b4',
    authDomain: 'eventease-571b4.firebaseapp.com',
    storageBucket: 'eventease-571b4.firebasestorage.app',
    measurementId: 'G-BLWNSH2JHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcMN5vc87JjSQfVQGwRs58Bz9q8tIrj6k',
    appId: '1:1033120432288:android:64b53863cd0f27154209c5',
    messagingSenderId: '1033120432288',
    projectId: 'eventease-571b4',
    storageBucket: 'eventease-571b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXIt_-kRNuZxDCq4Zp5ntiG2RlaKYjUs',
    appId: '1:1033120432288:ios:853bda441953bf144209c5',
    messagingSenderId: '1033120432288',
    projectId: 'eventease-571b4',
    storageBucket: 'eventease-571b4.firebasestorage.app',
    iosBundleId: 'com.example.eventease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYXIt_-kRNuZxDCq4Zp5ntiG2RlaKYjUs',
    appId: '1:1033120432288:ios:a079c32bd38b90124209c5',
    messagingSenderId: '1033120432288',
    projectId: 'eventease-571b4',
    storageBucket: 'eventease-571b4.firebasestorage.app',
    iosBundleId: 'com.example.eventease.RunnerTests',
  );
}
